
CREATE TABLE CYCLE_INFO (
	UID					NUMERIC(10)				NOT NULL,
	CYCLE_CODE			VARCHAR(10)				NOT NULL,
	CYCLE_DESCRIPTION	VARCHAR(50)						,
	CYCLE_DATE			DATE					NOT NULL,
	INSERT_DATE			TIMESTAMP				NOT NULL		DEFAULT 'NOW',
	LAST_INSERT			TIMESTAMP				NOT NULL		DEFAULT 'NOW'
);

ALTER TABLE CYCLE_INFO ADD CONSTRAINT CYCLE_INFO_PK PRIMARY KEY ( UID );
ALTER TABLE CYCLE_INFO ADD CONSTRAINT CYCLE_INFO_UK1 UNIQUE ( CYCLE_CODE, CYCLE_DATE );

CREATE INDEX CYCLE_INFO_IDX1 ON CYCLE_INFO ( CYCLE_CODE );
CREATE INDEX CYCLE_INFO_IDX2 ON CYCLE_INFO ( CYCLE_CODE, CYCLE_DATE );

CREATE SEQUENCE CYCLEINFO_SEQUENCE INCREMENT BY 1 START WITH 1;


CREATE TABLE CYCLE_PROCESSING_IDS (
	CYCLE_ID			NUMERIC(10)				NOT NULL,
	PROCESSING_ID		VARCHAR(10)				NOT NULL,
	INSERT_DATE			TIMESTAMP				NOT NULL		DEFAULT 'NOW'
);

ALTER TABLE CYCLE_PROCESSING_IDS ADD CONSTRAINT CYCLE_PROCESSING_IDS_PK PRIMARY KEY ( CYCLE_ID, PROCESSING_ID );
ALTER TABLE CYCLE_PROCESSING_IDS ADD CONSTRAINT CYCLE_PROCESSING_IDS_FK1 FOREIGN KEY ( CYCLE_ID ) REFERENCES
      CYCLE_INFO ( UID );

CREATE INDEX CYCLE_PROCESSING_IDS_IDX1 ON CYCLE_PROCESSING_IDS ( CYCLE_ID );